server:
  port: 9999
spring:
  on-profile: default
  datasource:
    url: jdbc:h2:mem:url_shorter_db
    driverClassName: org.h2.Driver

#    username: sa
#    password:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    h2:
      console:
        enabled: true
        path: /h2-console


#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:db/migration


  flyway:
    enabled: true
    url: jdbc:h2:mem:url_shorter_db
    #    username: sa
    #    password:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}    locations: classpath:db/migration


gcp:
  vars:
    admin.user: ${ADMIN_USERNAME:test@gmail.com}
    admin.password: ${ADMIN_PASSWORD:12345}

application:
  security:
    jwt:
      secret-key: c40d1f7126c036c2346949cae27036ed8048b3c76205a358fd0ea32aed3125c2
      expiration: 86400000 # a day
      refresh-token:

        expiration: 604800000 # 7 days

